### ISSUE TITLE
Improved error traceback for Python 2

### ISSUE THREAD

**Issue by RasmusN** [FlorianRhiem/pyGLFW#26]
The current traceback isn't so helpful when using Python 2. The traceback message typically looks something like this
```
Traceback (most recent call last):
  File "..\main.py", line 237, in process_user_input
    glfw.poll_events() # Get events from GLFW
  File "C:\Python27\lib\site-packages\glfw\__init__.py", line 1340, in poll_events
    _glfw.glfwPollEvents()
  File "C:\Python27\lib\site-packages\glfw\__init__.py", line 518, in errcheck
    _reraise(exc[1], exc[2])
  File "C:\Python27\lib\site-packages\glfw\__init__.py", line 51, in _reraise
    raise (exception, None, traceback)
TypeError: object.__init__() takes no parameters`
```
This issue arises since glfw re-raises the exception. Python 3 solves this by using raise exception.with_traceback(traceback). Solutions for this issue are discussed here https://stackoverflow.com/questions/18188563/how-to-re-raise-an-exception-in-nested-try-except-blocks

I tried Laurent LAPORTE's solution using the six-module and it seems to be working properly. However, I'm sure you want to avoid depending on this module.
```python
# glfw/__init__.py
import six
...
# Python 3 compatibility:
try:
    _getcwd = os.getcwdu
except AttributeError:
    _getcwd = os.getcwd
if sys.version_info.major > 2:
    _to_char_p = lambda s: s.encode('utf-8')
    def _reraise(exception, traceback):
        raise exception.with_traceback(traceback)
else:
    _to_char_p = lambda s: s
    def _reraise(exception, traceback):
        six.reraise(exception, None, traceback) 
        #raise (exception, None, traceback) # <- Old code
...
```
Perhaps there is some other way of solving this without using a 3rd part module?

**Comment by FlorianRhiem** [comment]
Thank you for pointing this out. Would the issue be solved by using the following code for Python 2?
```python
def _reraise(exception, traceback):
    # wrapped in exec, as python 3 does not support this variant of raise
    exec("raise exception, None, traceback")
```

**Comment by RasmusN** [comment]
Yes! That solution seems to work.
